### ISSUE TITLE
Replace Header BG Image

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#11]
Replace Header BG image with one attached.
![Uploading Evren_New Header BG Image.png…]()

**Comment by dallascasey** [comment]
Sorry, replace that image with this. And retitle for SEO if needed.
![Uploading Evren_New Header BG Image_V2.png…]()

**Comment by dallascasey** [comment]
Sorry, scratch those 2. Replace with this. Final one I swear. Lol.
![Uploading Evren_New Header BG Image_V3.png…]()

**Comment by webceyhan** [comment]
images are not uploaded correctly, redo lol

**Comment by dallascasey** [comment]
Ok, Try this:

![Uploading Evren_New Header BG Image_V4.png…]()

**Comment by dallascasey** [comment]
They're all stuck on "Uploading" for some reason. You might need to give me an email address I can send it to instead.

**Comment by dallascasey** [comment]
<img width="1425" alt="Evren_New Header BG Image_V4" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/f8a756b7-a4f4-4416-a3d1-01c44149450a">

**Comment by dallascasey** [comment]
Woo, that one finally worked!

**Comment by webceyhan** [comment]
done
