### ISSUE TITLE
Increase Sticky Menu Height

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#12]
1. Increase Sticky Menu height by 6px.

1.1. Add 3px to top.
1.2. Add 3px to bottom

2. Reduce White Sticky BG to 95% opacity, for subtle background see through effect.

3. Try & stop Sticky from loading on initial site load, on Desktop version.
<img width="1270" alt="Screen Shot 2024-07-07 at 1 20 16 am" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/5a6f0177-1081-42b4-8662-2fbe9201c6b5">

**Comment by webceyhan** [comment]
done
