### ISSUE TITLE
Investigate code in "Recent Projects" image to eliminate loading issues

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#17]
Have a look into code into code in "Recent Projects" images to see if you can find cause of loading issues, and repair. Screenshot attached.
<img width="1382" alt="Screen Shot 2024-07-07 at 2 08 59 am" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/b1258017-d491-4a91-9905-9de3cac8fdaf">

**Comment by webceyhan** [comment]
done
