### ISSUE TITLE
Raplace Image 1 in "Plaster Repairs" box

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#19]
Replace image 1 in "Plaster Repairs" box in section second from top with the one attached,
![Uploading Services_Image 1_V2.png…]()

**Comment by webceyhan** [comment]
you didn't attach the file correctly :)

**Comment by dallascasey** [comment]
Try this:

![Uploading Services_Image 1_V3.png…]()

**Comment by dallascasey** [comment]
![Services_Image 1_V3](https://github.com/dallascasey/dallascasey.github.io/assets/66746110/d9c76695-fc4b-48ee-881c-bd969c4fdd4d)

**Comment by dallascasey** [comment]
That one finally worked too.

**Comment by dallascasey** [comment]
Actually, replace with this. A fraction lighter...

**Comment by dallascasey** [comment]
![Services_Image 1_V4](https://github.com/dallascasey/dallascasey.github.io/assets/66746110/1659f052-8763-4862-9057-5002d1f70910)

**Comment by webceyhan** [comment]
changed
