### ISSUE TITLE
Help integrate SSL Certificate

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#20]
Help integrate an SSL Certificate to stop site being flagged on numerous browsers. I have no idea how to do this, but when I asked Crazy Domains about it, they told me to look for a "CSR File" or something. Hopefully you know what that is.

**Comment by webceyhan** [comment]
this needs to be setup in your hosting website, so i need your credentials

**Comment by dallascasey** [comment]
URL: crazydomains.com.au
UN: dallas1979
PW: Synik2026$

**Comment by webceyhan** [comment]
I've updated the DNS settings of your hosting, and now they are correctly pointing to your github page which is secured with SSL. So i'm closing the this issue
