### ISSUE TITLE
Mobile Headers Size Increase

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#25]
I just want a couple of slight increases to mobile header sizes of Sticky logo & "Surgery, For Spaces".

Use purple overlays in mockup attached as guides, and try & keep the same spacing/padding above & below "Surgery For Spaces" if possible.

![Evren_Mobile Header Size Increases](https://github.com/dallascasey/dallascasey.github.io/assets/66746110/910c90ee-a0b8-4b60-90e1-9a78ea838f73)

**Comment by webceyhan** [comment]
- i increased the font size of brand-heading from 40 to 42px
- logo is static image which cannot be modified this way.
