### ISSUE TITLE
Snap, Text, Quote size increase

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#26]
1. I just want a slight size increase to the "Snap, Text, Quote" title, using this purple overlay as a size guide.

2. If possible, move left feature image by 5-10px from top, or slightly crop off bottom of image.

<img width="1426" alt="Evren_Snap Text Quote Title_Increase" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/88f42093-9902-48d1-9cc6-a60f0061b6b4">

**Comment by webceyhan** [comment]
- font size increased from 63px to 65px
- left image is responsive and should not be re-positioned to support cross-device
