### ISSUE TITLE
"List of Services" text alignment

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#27]
Sorry, but I just want the body text in Complete list of Services section bumped left to the point of these purple lines if possible. My last layout looks just a little unbalanced.

![Uploading Evren_Services_Alingment Move.png…]()

**Comment by dallascasey** [comment]
<img width="1425" alt="Evren_Services_Alingment Move" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/e0757af6-8ea3-498a-9b9c-2eac98d2a2ec">

**Comment by webceyhan** [comment]
done
