### ISSUE TITLE
Change "Headache" to "Headaches" in section 3 body text.

### ISSUE THREAD

**Issue by dallascasey** [dallascasey/dallascasey.github.io#29]
See screenshot attached.

**Comment by dallascasey** [comment]
<img width="113" alt="Screen Shot 2024-07-07 at 1 32 33 pm" src="https://github.com/dallascasey/dallascasey.github.io/assets/66746110/34c34f05-ee67-4e60-b6c1-8b981e161a9d">

**Comment by webceyhan** [comment]
done
